### ISSUE TITLE
syntax error, unexpected '[' 

### ISSUE THREAD

**Issue by farlandliu** [metowolf/Meting#10]
Want to test this API, but failed. PHP=5.3.6
BTW, i'm not familiar to PHP.
```
<?php
// If you installed via composer, just use this code to requrie autoloader on the top of your projects.
//require 'mting.php';

//Or require file
require 'Meting.php';

use Metowolf\Meting;
//use Metowolf\Meting;

// Initialize to netease API
$API = new Meting('netease');

// Get data
$data = $API->format(true)->search('Soldier');

// Enjoy
echo $data;
?>

```
**Parse error: syntax error, unexpected '[' in .....\www\mting\Meting.php on line 703**

**Comment by metowolf** [comment]
@farlandliu As of PHP 5.4 it is possible to array dereference the result of a function or method call directly. It's bug, I will fix it later. But suggest upgrade your PHP to >=5.4.

**Comment by farlandliu** [comment]
@metowolf 
Thank you for prompt response!
How about PHP7? I'm thinking to upgrade PHP7.

**Comment by metowolf** [comment]
@farlandliu It works well on PHP7.

**Comment by QiuShiqi** [comment]
I have rewrited the incompatible code.

**Comment by metowolf** [comment]
Done.
