### ISSUE TITLE
网易云读取非自建歌单限制为20条目

### ISSUE THREAD

**Issue by lmcdn** [metowolf/Meting#103]
尝试了一下大佬的API(api.i-meto.com)，发现读取别人的歌单是全的，但是我用自己的来读取歌单最多读取到20个曲目，求问大佬原因

**Comment by metowolf** [comment]
这里确认下，是你自己调用 Meting 来获取只能读取到 20 个曲目吗。

**Comment by lmcdn** [comment]
是的，但是问题已经解决了，是写cookie的时候没加os=pc导致被网页版读取规则限制了，多谢大佬
