### ISSUE TITLE
这个程序不维护了吧？ 网易等接口早都失效了啊

### ISSUE THREAD

**Issue by sysalong** [metowolf/Meting#106]
这个程序不维护了吧？ 网易等接口早都失效了啊

现在最新的接口不是https://music.163.com/weapi/    地址应该是weapi 这个二级目录开始的吧

**Comment by metowolf** [comment]
没有失效的，接口是 web 端的 weapi

**Comment by vlssu** [comment]
> 没有失效的，接口是 web 端的 weapi

用不了是真的啊

**Comment by ericzane** [comment]
插件可以用啊，只是网易的歌单只有10首，虾米和百度就用不了了，QQ、酷狗、酷我的就都正常

**Comment by vlssu** [comment]
> 插件可以用啊，只是网易的歌单只有10首，虾米和百度就用不了了，QQ、酷狗、酷我的就都正常

现在修复了，我跟插件作者沟通过了，他修复了

**Comment by vlssu** [comment]
> 插件可以用啊，只是网易的歌单只有10首，虾米和百度就用不了了，QQ、酷狗、酷我的就都正常

现在修复了，我跟插件作者沟通过了，他修复了
