### ISSUE TITLE
Parse error: syntax error, unexpected '['

### ISSUE THREAD

**Issue by QiuShiqi** [metowolf/Meting#12]
低版本PHP出现不兼容，例如：
$url=json_decode($data, 1)['data']['song']['logo'];

需要修改为：
$json=json_decode($data, 1);
$url=json['data']['song']['logo'];

**Comment by liwanglin12** [comment]
@QiuShiqi We do not have plan to support PHP Version < 5.4.
Please upgrade your php.

**Comment by metowolf** [comment]
事实上已经修改了

**Comment by metowolf** [comment]
#10
