### ISSUE TITLE
网易接口出现奇怪问题

### ISSUE THREAD

**Issue by QiuShiqi** [metowolf/Meting#13]
我在返回的json数据中是能看到歌曲是存在320K版本的，但是用url方法只能得到一个192K版本的文件。我在url方法的第二个参数已经设置为9999了，但是没有效果，而且Meting项目的提交记录中是写着支持无损版本的。

**Comment by metowolf** [comment]
你出现的情况应该是 320k 的版本需要付费，可以在官方平台上验证一下，或者在这里提供一下歌曲 id 号

所谓支持无损版本是需要带上已经购买该歌曲的账号的cookie
目前 Meting 的目的只是搬运和集合各平台的 API，不会涉及破解版权限制的部分（本身用客户端无法播放的还是无法播放

**Comment by QiuShiqi** [comment]
谢谢你的回答。

**Comment by liwanglin12** [comment]
@metowolf closed this issue.
