### ISSUE TITLE
请求网易的api 时候url($id) 获取不到音乐链接。

### ISSUE THREAD

**Issue by DJ-clamp** [metowolf/Meting#15]
`{
"data": [
{
"id": 65795,
"url": null,
"br": 0,
"size": 0,
"md5": null,
"code": 404,
"expi": 1200,
"type": null,
"gain": 0,
"fee": 0,
"uf": null,
"payed": 0,
"flag": 0,
"canExtend": false
}
],
"code": 200
}`

返回数据如上所示，有点奇怪。。。。

**Comment by metowolf** [comment]
能否一并提供请求参数(id)，以便我重现排查

**Comment by DJ-clamp** [comment]
好的。
$data = $API->url('65795');

**Comment by metowolf** [comment]
官方接口做了改动，我稍后会进行修复

**Comment by DJ-clamp** [comment]
ok.知道了。

**Comment by D-Bood** [comment]
我这今天也出现这个问题了，用的是最新版
{"data":[{"id":468517654,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false}],"code":200}

**Comment by metowolf** [comment]
@D-Bood 经过测试没有出现这个问题
检查一下这几点：
 1. Meting 版本是否为 Version 1.3.3
 2. 尝试 http://music.163.com/#/song?id=468517654 是否能播放
 3. 服务器是否位于大陆外

**Comment by D-Bood** [comment]
@metowolf 好吧我的服务器在大陆外……
不过之前的版本是可以正常解析，很迷

**Comment by liwanglin12** [comment]
@D-Bood 因为修了这个issue导致的国外不可用，非常尴尬

**Comment by D-Bood** [comment]
@liwanglin12 所以我现在先用着1.3.2.1（

**Comment by liwanglin12** [comment]
@D-Bood 1321据说有一堆英文歌查不出来了

**Comment by D-Bood** [comment]
@liwanglin12 对我影响不大，我主要听日文

**Comment by D-Bood** [comment]
不好意思又来打扰了
我想问一下现在网易的api返回的音乐链接是http的还是https的？

**Comment by liwanglin12** [comment]
@D-Bood m7 / http
m8 / https

**Comment by liwanglin12** [comment]
@D-Bood You can replace in app https://github.com/liwanglin12/Hermit-X/blob/master/class.json.php#L41

**Comment by D-Bood** [comment]
@liwanglin12 ummm Thx for your share :)

**Comment by Nobiel** [comment]
@D-Bood But it seems this way doesn't work for my server in US. It still fails.

**Comment by D-Bood** [comment]
@Nobiel if u are abroad?
