### ISSUE TITLE
APIs doesn't word anymore 

### ISSUE THREAD

**Issue by hoootan** [metowolf/Meting#18]
hey bro, check your api , all of services except 'tencent' doesn't work properly , tencet api url has not 320 bitrate .. plz check it tnx 

<img width="185" alt="screen shot 2017-05-09 at 7 43 45 pm" src="https://cloud.githubusercontent.com/assets/15173179/25857995/e1d7ede6-34ef-11e7-84a9-1a9e6e3e16c1.png">
<img width="210" alt="screen shot 2017-05-09 at 7 43 53 pm" src="https://cloud.githubusercontent.com/assets/15173179/25857997/e2476bda-34ef-11e7-89d9-0dea45bfa4a4.png">

**Comment by metowolf** [comment]
Can you post your params or songID? Like `$Meting("tencent")->search("example")`

**Comment by hoootan** [comment]
I can get song details but when I use `$Meting("tencent")->url(music id)` ,but response is what i sent for you!

**Comment by metowolf** [comment]
Maybe you need a **chinese proxy** because of copyright.

**Comment by hoootan** [comment]
I will test it, thanks for the answer

**Comment by hoootan** [comment]
<img width="546" alt="screen shot 2017-05-09 at 9 03 53 pm" src="https://cloud.githubusercontent.com/assets/15173179/25861811/1a5f4b9a-34fb-11e7-8b7d-34d84bd0a26b.png">

**Comment by metowolf** [comment]
It's proxy problem :man_facepalming:
