### ISSUE TITLE
Tencent Music 搜索结果为空时进行格式化报错 Notice: Undefined index

### ISSUE THREAD

**Issue by freejishu** [metowolf/Meting#19]
我知道这个问题不大，关掉报错就好了，不过强迫症还是想办法收拾一下
自己PHP水平一般，大神如果有更好的写法还请指导（也正因此没有发PR）
语句：
$data=$Tencent->format(1)->search("dbiusbdisdfidhiuhfn");

报错信息：
Notice: Undefined index: songmid in /Meting.php on line 1004
Notice: Undefined index: songname in /Meting.php on line 1005
Notice: Undefined index: albummid in /Meting.php on line 1007
Notice: Undefined index: songmid in /Meting.php on line 1008
Notice: Undefined index: songmid in /Meting.php on line 1009
Notice: Undefined index: singer in /Meting.php on line 1012
Warning: Invalid argument supplied for foreach() in /Meting.php on line 1012

解决方案：加一个判断，如果$data为空则返回全空，否则返回正常数据。

    private function format_tencent($data)
    {
        if (isset($data['musicData'])) {
            $data=$data['musicData'];
        }
        if($data){
            $result=array(
                'id'        => $data['songmid'] ? $data['songmid'] : null,
                'name'      => $data['songname'],
                'artist'    => array(),
                'pic_id'    => $data['albummid'],
                'url_id'    => $data['songmid'],
                'lyric_id'  => $data['songmid'],
                'source'    => 'tencent',
            );
            foreach ($data['singer'] as $vo) {
                $result['artist'][]=$vo['name'];
            }
            return $result;
        }else{
            $result=array(
                'id'        => null,
                'name'      => null,
                'artist'    => null,
                'pic_id'    => null,
                'url_id'    => null,
                'lyric_id'  => null,
                'source'    => 'tencent',
            );
            return $result;
        }
    }

暂时不清楚其他的格式化是否存在相应问题。
Meting很好用，省掉了大量的抓包破js时间，十分感谢。

**Comment by liwanglin12** [comment]
@freejishu meto: 不加，懒

**Comment by metowolf** [comment]
下个版本就着重解决所有警告问题
