### ISSUE TITLE
网易云音乐里获取专辑图片不正确

### ISSUE THREAD

**Issue by SLT2** [metowolf/Meting#21]
在wiki里的获取 专辑图片在代码，
$id=28535;
$data = $API->pic($id);
echo $data;
输出的结果是https://p3.music.126.net/6vxf0W45d7u_o-NZiRJgkQ==/28535.jpg?param=300z300&quality=100
不是有效图片，真实的专辑图片是http://p1.music.126.net/rpN_SSV-plUaFsw06NXZqQ==/37383395345629.jpg 
在获取专辑信息里$API->album($id);输出的“blurPicUrl”才是真实的专辑图片。

**Comment by SLT2** [comment]
第693行代码开始，可以修改为：
case 'netease':
$format=$this->_FORMAT;
$data=$this->format(false)->album($id);
$this->format($format);
$data=json_decode($data, 1);
$url=$data['album']['blurPicUrl'];
break;
输出结果：
{"url":"http:\/\/p1.music.126.net\/rpN_SSV-plUaFsw06NXZqQ==\/37383395345629.jpg"}

**Comment by liwanglin12** [comment]
@SLT2 @metowolf 文档写错了快出来改

**Comment by metowolf** [comment]
@SLT2 这里的 ID 指的是图片 ID，而不是歌曲或者专辑 ID，图片 ID 可以调用 song 接口后查看 pic_id

**Comment by SLT2** [comment]
@metowolf 嗯dalao，找到了，还可以设置尺寸。
