### ISSUE TITLE
请问网易云音乐的最新歌单在API在哪？

### ISSUE THREAD

**Issue by SLT2** [metowolf/Meting#22]
在你的demo中：https://music.i-meto.com/netease
可以获取到最新歌单的列表，但文档和代码里都没有写，请问是怎么做到的？

**Comment by metowolf** [comment]
这个可以在 music.163.com 抓包重放得到

**Comment by SLT2** [comment]
研究了好久，还是不会抓包

**Comment by metowolf** [comment]
有个比较老的但是依旧有效的 API，如下
http://music.163.com/api/playlist/list?cat=%E5%85%A8%E9%83%A8&order=hot&offset=0&total=true&limit=50
