### ISSUE TITLE
启用插件没反应

### ISSUE THREAD

**Issue by NeduTestLab** [metowolf/Meting#23]
你好，我将插件启用之后，在编辑栏是出现一个音乐按钮，点击添加音乐，然后预览什么都没有，发布文章之后也是不显示音乐播放器，也没有声音，这是什么原因呐？请赐教，谢谢

**Comment by metowolf** [comment]
可能是插件中的 Meting.php 库出现问题，稍后我发布一个更新。
未来考虑会采用云解析的方式

**Comment by NeduTestLab** [comment]
谢谢，更新之后，麻烦在github上通知下

2017-06-01 13:05 GMT+08:00 METO <notifications@github.com>:

**Comment by metowolf** [comment]
已经添加云解析功能，欢迎使用
