### ISSUE TITLE
希望格式化内容能增加歌曲所属的专辑名

### ISSUE THREAD

**Issue by ericzane** [metowolf/Meting#24]
这是个基本内容，现在我只能用其他途径API获取
另外希望尽量能把歌曲地址转换为https（貌似除了酷狗其他都可以）

**Comment by liwanglin12** [comment]
@ericzane Are you sure TLS is available in Tencent&Baidu？

**Comment by ericzane** [comment]
@liwanglin12 
http://eric.cn.com/
我的插件已经转换过了，除了酷狗，其他都是可以的，Meting本身输出的百度就是https的

**Comment by liwanglin12** [comment]
@ericzane In fact, Meting returned HTTPS in few versions ago. But for overseas users, we decided to return the protocol which from the provider server.

**Comment by ericzane** [comment]
@liwanglin12  你确定目前的Meting支持海外服务器？
http://blog.ericz.tk/
我同样版本的插件在openshift.redhat.com上的服务器获取数据是失败的
http://twins.cn.com/
而在同样服务器上旧版插件（没用Meting）是正常的

**Comment by liwanglin12** [comment]
@ericzane Netease HTTPS url can't play if user in overseas

**Comment by Shy07** [comment]
Excuse me, but my jp vultr server was ok when I sent a request with 'X-Real-IP' header.
modified Meting, line 64-66
https://github.com/D-Bood/Musicoon/blob/master/src/Meting.php
use HTTPS url, line 22-23
https://github.com/D-Bood/Musicoon/blob/master/src/player.php

thx @D-Bood

**Comment by metowolf** [comment]
@ericzane 经过测试，当前的 API 是可以直接支持海外服务器的
关于 “尽量能把歌曲地址转换为https”，当时是考虑到部分 https 并没有部署到国外 CDN 上，现在看起来都可以了

**Comment by D-Bood** [comment]
@Shy07 这个方法也是从[别的地方](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%b0%83%e7%94%a8%e5%89%8d%e9%a1%bb%e7%9f%a5)看过来的。不过还有一个遗憾的地方就是专辑图片加载不出来……

**Comment by metowolf** [comment]
@D-Bood 专辑图片似乎也是仅国内才有 https

**Comment by D-Bood** [comment]
@metowolf 解析还是可以解析出来的，就是用国外IP访问会超时。
