### ISSUE TITLE
酷狗的搜索用中文关键字需要格式转换

### ISSUE THREAD

**Issue by ericzane** [metowolf/Meting#25]
$data = $api->format(true)->search('张靓颖')
这样是得不到结果的
$data = $api->format(true)->search('C AllStar')
这样没问题

**Comment by metowolf** [comment]
我记得以前不用的啊 :sob:

**Comment by ericzane** [comment]
亲测的，其他不用， 就酷狗要

**Comment by metowolf** [comment]
刚才做了测试，是可以正常返回结果的，可能是 API 或 PHP 环境问题，事实上内部已经做了编码
https://github.com/metowolf/Meting/blob/master/src/Meting.php#L61

**Comment by ericzane** [comment]
<?php
require 'Meting.php';
use Metowolf\Meting;
$api = new Meting('kugou');
$data = $api->format(true)->search('张靓颖');
$data = json_decode($data,1);
print_r($data); 
?>
我做的测试php是没返回结果的
http://eric.cn.com/1.php

**Comment by ericzane** [comment]
`<?php
require 'Meting.php';
use Metowolf\Meting;
$api = new Meting('kugou');
$data = $api->format(true)->search('张靓颖');
$data = json_decode($data,1);
print_r($data); 
?>`
http://eric.cn.com/1.php
我做的测试文件没有结果，改英文的就可以

**Comment by metowolf** [comment]
你尝试访问 http://ioscdn.kugou.com/api/v3/search/song?iscorrect=1&pagesize=30&plat=2&tag=1&sver=5&showtype=10&page=1&keyword=%E5%BC%A0%E9%9D%93%E9%A2%96&version=8550
看有没有结果，本地和服务器都试一下

**Comment by ericzane** [comment]
我测试过的，用$_GET方式获得的中文是没问题的，但用赋值出来的$就失败，现在我的解决方式就是粗暴的解码重编码
`$str = mb_convert_encoding($str, 'utf-8', mb_detect_encoding($str, array('UTF-8', 'GBK', 'LATIN1', 'BIG5')));`
这样就可以用了

**Comment by ericzane** [comment]
`<?php
require 'Meting.php';
use Metowolf\Meting;
$api = new Meting('kugou');
$str = '张靓颖';
$str = mb_convert_encoding($str, 'utf-8', mb_detect_encoding($str, array('UTF-8', 'GBK', 'LATIN1', 'BIG5')));
$data = $api->format(true)->search($str);
$data = json_decode($data,1);
print_r($data); 
?>`
这个样子

**Comment by metowolf** [comment]
如果这样能成功的话，就说明是你服务器中文编码问题了，而且酷狗对参数要求较为严格
