### ISSUE TITLE
网易云音乐无法获取歌词

### ISSUE THREAD

**Issue by Tokinx** [metowolf/Meting#29]
如标题，其它平台不知道，网易的歌词好像是获取不到了。

**Comment by liwanglin12** [comment]
@Tokinx SHEEL METO:
我这好像能用
你给个复现实例

**Comment by Tokinx** [comment]
找到问题了，好像是网易改版导致JSON嵌套层级变了，之前是 lrc->lyric，现在直接是 lyric 了，非常感谢。
