### ISSUE TITLE
Getting album pic failed

### ISSUE THREAD

**Issue by D-Bood** [metowolf/Meting#3]
Hi!
I use
`$API->pic($id);`
to get the album pic. But when I open the link there's nothing and the debugger returns me a 404.
I choose Netease and my server isn't in China. My PHP version is 7.1.0
Thanks your hard work!

**Comment by metowolf** [comment]
Please paste your $id and result detail, that I can debug it

**Comment by D-Bood** [comment]
Well, it seems there's a lot of $id...
for example
$id = 41629793
return = "https://p3.music.126.net/_RyoMOWQqMhv3KzrpOBaEw==/41629793.jpg?param=300z300&quality=100"
And when I open the link, the debugger tells: "Failed to load resource: the server responded with a status of 404 (Not Found)"

**Comment by metowolf** [comment]
It seems you use the wrong id. 
The $id means pic_id which different to album_id, and you can get it with $API->format(true)->xxx()

**Comment by liwanglin12** [comment]
@metowolf define('xxx','song'); ?

**Comment by D-Bood** [comment]
the $id i used isn't album_id, it's song_id. and the wiki also is written that
参数名	必须	        含义
    id	          是	     **歌曲编号**

**Comment by liwanglin12** [comment]
@D-Bood 老司机翻车

**Comment by D-Bood** [comment]
@liwanglin12 好吧……这就尴尬了（

**Comment by metowolf** [comment]
我的锅，已经修复_(´ཀ`」 ∠)_ 
歌词，图片，下载地址同理
感谢
