### ISSUE TITLE
PHPUnit\Framework\TestCase 文件不存在

### ISSUE THREAD

**Issue by ihewro** [metowolf/Meting#31]
测试用例里面的`PHPUnit\Framework\TestCase`类文件没有上传到github上面吧？

```
http://localhost/meting/tests/NeteaseTest.php
```

提示错误：
```
Fatal error: Class 'PHPUnit\Framework\TestCase' not found in /Applications/XAMPP/xamppfiles/htdocs/meting/tests/NeteaseTest.php on line 6
```

**Comment by metowolf** [comment]
You probably run it without PHPUnit local.

I suggest that you download PHPUnit with the the version 5.7 (which is supported on PHP 5.6, PHP 7.0, and PHP 7.1.). Then run `php phpunit-5.7.phar` in document root.

OR, maybe you just want to test it.
Follow https://github.com/metowolf/Meting#quick-start

**Comment by ihewro** [comment]
Thank you for your repley.

But the follwing code maby is a small fault,because I cant't find this file in this project.

```
require 'vendor/autoload.php';
```

The correct code maybe is 

```
require 'Meting.php';
```

**Comment by ihewro** [comment]
sorry ,it's my falut.

I just now konw generating `vendor/autoload.php` by running Composer tool.
