### ISSUE TITLE
Why fail to get data?

### ISSUE THREAD

**Issue by ihewro** [metowolf/Meting#32]
I download the project. and create a new php file, this is my test code:

```php
<?php 

require './src/Meting.php';
use Metowolf\Meting;

// Initialize to netease API
$api = new Meting('netease');

// Use custom cookie (option)
$api->cookie('paste your cookie');

// Get data
$data = $api->format(true)->search('Soldier');

// Enjoy
echo $data;

?>
```

when I run the server, I can not get the correct data:

```
{"error":7,"info":{"url":"http:\/\/music.163.com\/api\/linux\/forward","content_type":null,"http_code":0,"header_size":0,"request_size":0,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":0,"namelookup_time":1.9e-5,"connect_time":0,"pretransfer_time":0,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":-1,"upload_content_length":-1,"starttransfer_time":0,"redirect_time":0,"redirect_url":"","primary_ip":"","certinfo":[],"primary_port":0,"local_ip":"","local_port":0},"status":""}
```

What should I do ?

Thank you !

**Comment by metowolf** [comment]
> CURL error code 7 (CURLE_COULDNT_CONNECT)

is very explicit ... it means Failed to connect() to host or proxy.

The following code would work on any system:

```php
<?php
$ch=curl_init("http://music.163.com");
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
$data = curl_exec($ch);
print($data);
```

If you can not see netease music page then .. you have some firewall or network issue.

**Comment by ihewro** [comment]
我在test.php中加入上面代码，测试之后，打开这个网址
```
localhost/meting/tests/test.php
```

确实没有跳转到网易云的界面，而是跳转到本地服务器的默认页面

![jietu20171013-202236](https://user-images.githubusercontent.com/20165605/31546044-597e5336-afe7-11e7-9459-8bfd52333e9d.jpg)

我怀疑是网易云服务器的设置，导致的不能成功发起请求。不知道您这边测试是否成功呢？

本地网络应该是没有问题的，测试很多其他网址，也能正常在浏览器中打开网易云音乐的网站？

**Comment by ihewro** [comment]
好吧，现在已经恢复了。

可能是我这边网络的问题，也可能是网易云服务器问题。

非常感谢！
