### ISSUE TITLE
获取的音乐地址正确  但是h5 的audio 有时候无法播放

### ISSUE THREAD

**Issue by IFmiss** [metowolf/Meting#33]
![image](https://user-images.githubusercontent.com/17402583/31755979-f36c7bbc-b4d3-11e7-9842-7123a12ab771.png)

有时候会报403错误   但是地址确实是对的，这种错在前端没有规律，不知道是什么原因

**Comment by metowolf** [comment]
可以自行做替换，具体规则是 m7c -> m7, m8c -> m8
网易云对上面两个地址做了防盗链

**Comment by liwanglin12** [comment]
要是没有防盗链的话这两个url其实是最佳选择

**Comment by IFmiss** [comment]
感谢  解决了这个问题了！太好了！
