### ISSUE TITLE
网易云音乐图片ID有效位溢出问题

### ISSUE THREAD

**Issue by RayLee3306** [metowolf/Meting#34]
部分网易云的图片ID在32位系统下经过json_decode处理之后由于超大溢出变成了科学计数法，有效精度丢失导致无法还原回原来的ID了，建议需要单独处理这部分ID，强制转换为字符串。调试数据如下：

`{"songs":[{"name":"Time","id":1426503,"pst":0,"t":0,"ar":[{"id":34517,"name":"Hans Zimmer","tns":[],"alias":[]}],"alia":["《盗梦空间》插曲"],"pop":100.0,"st":0,"rt":"","fee":8,"v":27,"crbt":null,"cf":"","al":{"id":146120,"name":"Inception (Music From The Motion Picture)","tns":["电影《盗梦空间》原声带"],"pic":6659741929670226},"dt":275546,"h":{"br":320000,"fid":0,"size":11024762,"vd":0.07},"m":{"br":160000,"fid":0,"size":5512404,"vd":0.0422504},"l":{"br":96000,"fid":0,"size":3307460,"vd":-2.65076E-4},"a":null,"cd":"1","no":12,"rtUrl":null,"ftype":0,"rtUrls":[],"djId":0,"copyright":1,"s_id":0,"rtype":0,"rurl":null,"mst":9,"cp":7002,"mv":0}],"privileges":[{"id":1426503,"fee":8,"payed":0,"st":0,"pl":128000,"dl":0,"sp":7,"cp":1,"subp":1,"cs":false,"maxbr":999000,"fl":128000,"toast":false,"flag":0}],"code":200}`

json_decode之后：

`["al"]=> array(4) { ["id"]=>int(146120) ["name"]=>string(41) "Inception (Music From The Motion Picture)" ["tns"]=>array(1) {[0]=>string(33) "电影《盗梦空间》原声带" } ["pic"]=>float(6.6597419296702E+15)}`

在json_decode前$data=preg_replace('/(\"pic\"\:)([0-9]+)/', '$1"$2"', $data)单独处理pic之后：

`{"songs":[{"name":"Time","id":1426503,"pst":0,"t":0,"ar":[{"id":34517,"name":"Hans Zimmer","tns":[],"alias":[]}],"alia":["《盗梦空间》插曲"],"pop":100.0,"st":0,"rt":"","fee":8,"v":27,"crbt":null,"cf":"","al":{"id":146120,"name":"Inception (Music From The Motion Picture)","tns":["电影《盗梦空间》原声带"],"pic":"6659741929670226"},"dt":275546,"h":{"br":320000,"fid":0,"size":11024762,"vd":0.07},"m":{"br":160000,"fid":0,"size":5512404,"vd":0.0422504},"l":{"br":96000,"fid":0,"size":3307460,"vd":-2.65076E-4},"a":null,"cd":"1","no":12,"rtUrl":null,"ftype":0,"rtUrls":[],"djId":0,"copyright":1,"s_id":0,"rtype":0,"rurl":null,"mst":9,"cp":7002,"mv":0}],"privileges":[{"id":1426503,"fee":8,"payed":0,"st":0,"pl":128000,"dl":0,"sp":7,"cp":1,"subp":1,"cs":false,"maxbr":999000,"fl":128000,"toast":false,"flag":0}],"code":200}`

`["al"]=>array(4) { ["id"]=>int(146120) ["name"]=>string(41) "Inception (Music From The Motion Picture)"
 ["tns"]=>array(1) {[0]=>string(33) "电影《盗梦空间》原声带"} ["pic"]=>string(16)"6659741929670226"}`

**Comment by metowolf** [comment]
The JSON_BIGINT_AS_STRING flag can fixed the problem.
```php
$json = '{"pic": 12345678901234567890}';
json_decode($json);
// float(1.2345678901235E+19)
json_decode($json, false, 512, JSON_BIGINT_AS_STRING);
// string(20) "12345678901234567890"
```

But I use another method in Meting
https://github.com/metowolf/Meting/blob/master/src/Meting.php#L1079-L1081
