### ISSUE TITLE
能否获取网易云banner的最新信息

### ISSUE THREAD

**Issue by IFmiss** [metowolf/Meting#35]
你好  我能否获取网易云的banner信息，想做一个banner列表

**Comment by metowolf** [comment]
如果只是需要固定获取 banner 信息，只需要抓包找到那条 post 记录重放即可，目前 API 并没有防重放处理，但这个不在该项目的范畴。

**Comment by liwanglin12** [comment]
@metowolf @metowolf will close this issue.
