### ISSUE TITLE
ID3

### ISSUE THREAD

**Issue by hoootan** [metowolf/Meting#36]
hey buddy, why any of api's have not any artwork and correct ID3 tag ? their mp3 files have nothing! just song :))

**Comment by liwanglin12** [comment]
@hoootan You need to consult the relevant music provider.

**Comment by hoootan** [comment]
@liwanglin12 you are right but these APIs export music url and dump main database and i think this problem is form music provider database! because any MP3 file should have all tags and artwork.
in this way I have to stick image, artist name and song name manually to mp3 file from my own server.

**Comment by liwanglin12** [comment]
@hoootan Which country are you in? In fact, China's music provider technology is not very satisfactory.

**Comment by metowolf** [comment]
As far as I know, Netease (music.163.com) don't supply ID3 metadata, but Tencent (y.qq.com) does.
It is music provider's problem. TAT

**Comment by liwanglin12** [comment]
@metowolf Perhaps you can contact Netease customer service cloudmusicservice@163.com on this issue. However, I suggest not to mention Meting Framework in your email😋

**Comment by hoootan** [comment]
@liwanglin12 I'm in Iran, yes I agree with you, my users muttering me everyday:"why most of music doesn't have artwork or blah blah blah =))))

**Comment by liwanglin12** [comment]
@hoootan ｡ﾟ(ﾟ´Д｀ﾟ)ﾟ｡
