### ISSUE TITLE
网易云获取歌曲信息 function song($id) 获取数据失败，返回值 -460

### ISSUE THREAD

**Issue by IFmiss** [metowolf/Meting#39]
![image](https://user-images.githubusercontent.com/17402583/34600661-7e5edb92-f233-11e7-8d67-8a29e70657e8.png)

现在音频数据可以获取到，但是点击播放获取详细信息没办法获取   也就今天才开始无法播放

**Comment by Genteure** [comment]
@IFmiss 请更新 Meting 到最新版本

**Comment by IFmiss** [comment]
ok 已经好了！感谢

**Comment by IFmiss** [comment]
你好  这个问题又出现了   详情请见  [http://www.daiwei.org/#/music/sheet/124995419](url)  
![image](https://user-images.githubusercontent.com/17402583/35790160-cf4d9768-0a7b-11e8-8184-9fb5611b68f3.png)

**Comment by mashirozx** [comment]
歌单接口崩了

**Comment by IFmiss** [comment]
虽然没有报错  但现在只显示一首歌曲    今天上午还好好的

**Comment by metowolf** [comment]
大概是再次封掉了，建议传入一个正常的 cookie 使用

**Comment by IFmiss** [comment]
请问大概如何操作？

**Comment by IFmiss** [comment]
对于一个不懂后台代码的人   看的还是不太懂，有没有什么联系方式详细请教一下吗

**Comment by freejishu** [comment]
@IFmiss 
e.g.

```
use Metowolf\Meting;

$api = new Meting('netease');

$api->cookie('_Here is your cookies_')

$data = $api->format(true)->search('Secret time');
```

Cookies can catch in many software(e.g. chrome to view http://music.163.com).

**Comment by IFmiss** [comment]
@freejishu  我试了一下 真的可以了  老铁666
