### ISSUE TITLE
调用失败

### ISSUE THREAD

**Issue by ericzane** [metowolf/Meting#41]
更新版本后获取数据失败 测试发现提示：
Parse error: syntax error, unexpected '[' in /htdocs/Meting.php on line 74
该行改用下面格式后正常
        $httpheader[] = 'Accept: */*';
        $httpheader[] = 'Accept-Encoding: gzip, deflate';
        $httpheader[] = 'Accept-Language: zh-CN,zh;q=0.8,gl;q=0.6,zh-TW;q=0.4';
        $httpheader[] = 'Connection: keep-alive';
        $httpheader[] = 'Content-Type: application/x-www-form-urlencoded';
        $httpheader[] = 'Referer: ' . $BASE['referer'];
        $httpheader[] = 'User-Agent: ' . $BASE['useragent'];
        curl_setopt($curl, CURLOPT_HTTPHEADER, $httpheader);

**Comment by metowolf** [comment]
Hi @ericzane 

It looks like you are running PHP version 5.3 or less?
Considering PHP 5.3 support was dropped long ago, I'd strongly advise you upgrade to PHP 7. If you can't do this, then replacing `[ ]` with `array( )` might resolve your issue, but it's probable there are other areas that require a newer version of PHP.

**Comment by ericzane** [comment]
OK，我的服务器可选择版本是5.2-5.5，之前默认5.3，现在改为5.5没问题了
