### ISSUE TITLE
百度的防盗链如何解决

### ISSUE THREAD

**Issue by ericzane** [metowolf/Meting#42]
跟#33类似 现在的API输出的百度歌曲url只能直接下载 无法播放

**Comment by ericzane** [comment]
![011](https://user-images.githubusercontent.com/21684243/35982812-a68b2ebe-0d2b-11e8-9a13-72abf8adb71a.jpg)

**Comment by metowolf** [comment]
Replacing `http://yinyueshiting.qianqian.com` with `https://gss0.bdstatic.com/y0s1hSulBw92lNKgpU_Z2jR7b2w6buu` might solve this problem.

**Comment by ericzane** [comment]
OK，解决了 但不是http://yinyueshiting.qianqian.com 而是http://zhangmenshiting.qianqian.com
