### ISSUE TITLE
关于孟坤播放器网页版歌单读取失败-200反馈

### ISSUE THREAD

**Issue by kejily** [metowolf/Meting#48]
最近孟坤播放器网页版经常听说歌单读取失败-200，换句话说就是有时候无法获取网易云音乐的的歌曲地址，这个跟cookie有关系吗？我在meting.php里面换上自己的cookie还是行不通，有时候可以，有时候不可以，假如我现在有两个网站用了孟坤的播放器网页版，如果这个时候不能读取到网易云音乐的的歌曲地址，换另外一个网站却又可以用，好像同时在线播放的人数不能过多，不然就获取不到网易云音乐的歌曲地址

**Comment by metowolf** [comment]
建议在 https://github.com/mengkunsoft/MKOnlineMusicPlayer/issues 进行反馈

通常是请求过于频繁导致的，可以考虑 Cache 一部分请求
