### ISSUE TITLE
网易api   search方法分页重复

### ISSUE THREAD

**Issue by IFmiss** [metowolf/Meting#49]
search方法的分页无论page设置为多少都是重复的

**Comment by metowolf** [comment]
这里没有重现你的问题，可以检查是否更新了新的 search 方法

```php
$data = $api->format(true)->search('Soldier', [
    'page' => 1,
    'limit' => 50
]);
```

**Comment by IFmiss** [comment]
![image](https://user-images.githubusercontent.com/17402583/38970526-9db656a0-43c8-11e8-830e-6e0a234a8814.png)
![image](https://user-images.githubusercontent.com/17402583/38970544-b15e38f8-43c8-11e8-8fae-d8b6e93acfc3.png)
$API->search($s, $pages, $limit);  这个三个参数都变化了 但是返回的数据还是page1 的数据   还是我这个方法有问题？  这几个参数的值是没有问题的

**Comment by IFmiss** [comment]
http://www.daiwei.org/vue/server/music.php?inAjax=1&do=search&count=30&pages=2&name=%E7%88%B1%E7%9A%84%E6%95%85%E4%BA%8B 
这是接口地址

**Comment by metowolf** [comment]
应该把 `$API->search($s, $pages, $limit);` 改为 
```
$API->search($s, array(
    'page' => $pages,
    'limit' => $limit
));
```

**Comment by IFmiss** [comment]
@metowolf 我换成
$API->search($s, array(
    'page' => $pages,
    'limit' => $limit
));

还是一样的结果

**Comment by metowolf** [comment]
试了你的接口地址，不是有变化吗。本地测试也正常。

**Comment by IFmiss** [comment]
可以了  我刚测试的时候接口写死了pages的值  现在可以了， 感谢
另外可以互换友链吗？

**Comment by fung626** [comment]
@IFmiss How can you get the `songCount` data in your API ?

**Comment by IFmiss** [comment]
@fung626  $limit    $limit = getParam('count', 20);  //每页显示数量
