### ISSUE TITLE
如何获取播放列表封面

### ISSUE THREAD

**Issue by Tokinx** [metowolf/Meting#5]
试着用format(0)->playlist('列表ID')，没有找到列表封面的pic id，album('列表ID')也不行，有什么方法么？

**Comment by metowolf** [comment]
应该是有的，比如网易云（列表id:84051656），不过目前还没有整合在 format 函数里面，需要自行在原始数据里调用
```
 + result
    + coverImgUrl: http://p3.music.126.net/oSeIkeeD2zRi8efe44mY-g==/109951162863991742.jpg
```

**Comment by Tokinx** [comment]
感谢，找到了，之前没注意到coverImgId
