### ISSUE TITLE
Pagination Problem

### ISSUE THREAD

**Issue by fung626** [metowolf/Meting#52]
I want to setup a pagination search function in my application. And I have finished API part by follow your instruction

```
$api = new Meting('netease');

$data = $api->format(true)->search('Soldier', [
    'page' => 1,
    'limit' => 50
]);

echo $data;
```

The data have successfully received. However, without the `total` I can't calculate the last page. Same as your [NeteaseCloudMusicApi](https://github.com/metowolf/NeteaseCloudMusicApi) repo `songCount` data. 

Also, I had reviewed Meting.php. And I found out there is a parameter call `total` in netease. By default set it to true, but I still can't get the `total`. 

My question is how I get the `total` when run the search function? thanks in advance

**Comment by metowolf** [comment]
set format with false, the `total` is in `res.data.song.totalnum`

```php
$data = $api->format(false)->search('Soldier', [
    'page' => 1,
    'limit' => 30
]);
```

```json
{
   "subcode" : 0,
   "code" : 0,
   "message" : "",
   "tips" : "",
   "notice" : "",
   "data" : {
      "totaltime" : 0,
      "keyword" : "Soldier",
      "song" : {
         "curnum" : 1,
         "totalnum" : 396,
         "list" : [
            {
              ...
            }
         ],
         "curpage" : 1
      },
      "priority" : 0,
      "qc" : [],
      "tab" : 0,
      "semantic" : {
         "list" : [],
         "totalnum" : 0,
         "curnum" : 0,
         "curpage" : 1
      },
      "taglist" : []
   }
}

```

**Comment by fung626** [comment]
How about the other sources ? Only netease return `total` ?

**Comment by metowolf** [comment]
Try yourself without format 😆

**Comment by fung626** [comment]
thx for help :)
