### ISSUE TITLE
返回歌词中有转义HTML

### ISSUE THREAD

**Issue by ZhangZisu** [metowolf/Meting#53]
Meting API 返回的歌词中会有转义HTML

如
![image](https://user-images.githubusercontent.com/21094314/40814830-3e0fa16a-6575-11e8-90c2-01fcedfe689b.png)

会导致APlayer歌词渲染错误
![image](https://user-images.githubusercontent.com/21094314/40814888-80c0dea2-6575-11e8-8dad-b02eb9b8b10d.png)

**Comment by metowolf** [comment]
@ZhangZisu Please offer your lyric id.

**Comment by ZhangZisu** [comment]
Server: `tencent`

Type: `song`

ID: `000g1DFI1H5W88`

Request URL:`https://api.i-meto.com/meting/api?server=tencent&type=song&id=000g1DFI1H5W88&r=0`

Lyric URL: `https://bach.meting.cdn.fj.cn//api.php?server=tencent&type=lrc&id=000g1DFI1H5W88&auth=4f82838d`

**Comment by metowolf** [comment]
QQ Music API returns many HTML entities, it should be fixed in other program.

```php
return html_entity_decode($lyric, ENT_QUOTES | ENT_HTML5);
```

PS: METO API will be fixed later on. XD

**Comment by liwanglin12** [comment]
@metowolf PS: Hermit X & LWL API will be fixed later on. XD
