### ISSUE TITLE
请问Linux版的云音乐API是怎么得到的？

### ISSUE THREAD

**Issue by hufan-Akari** [metowolf/Meting#6]
研究 weapi 的时候，发现 weapi 少了很多东西，

Linux 版的云音乐貌似是全功能的，我想得到更多的 API，请问怎么拿到这些接口？

**Comment by liwanglin12** [comment]
@hufan-Akari Just analyze by yourself :-)

**Comment by metowolf** [comment]
@hufan-Akari 抓包，用密钥 dump 出原请求参数
别的不能说太多了 :laughing:
