### ISSUE TITLE
api接口请求一直超时

### ISSUE THREAD

**Issue by booboom** [metowolf/Meting#60]
本地运行的博客和托管到github上的博客都报这个错，不管是http协议还是https协议：
![image](https://user-images.githubusercontent.com/24515720/47011960-b9008d00-d175-11e8-838d-7f5c55907d02.png)

但是在接口测试工具上能够正常请求：
![image](https://user-images.githubusercontent.com/24515720/47012008-d7ff1f00-d175-11e8-94d1-1c27db519f8a.png)

大佬们有没有知道怎么解决啊？

**Comment by metowolf** [comment]
通常是大陆互联网与国际互联网之间的网络问题

由于该问题与 Meting 无关，该 issue 先做关闭处理。
