### ISSUE TITLE
api报错net::ERR_TIMED_OUT

### ISSUE THREAD

**Issue by booboom** [metowolf/Meting#61]
如题，
本地和托管在GitHub上的博客都报这个错误：
Meting.min.js:1 GET https://api.i-meto.com/meting/api?server=netease&type=playlist&id=536254974&r=0.5307348801325908 net::ERR_TIMED_OUT
接口测试工具可以正常访问

**Comment by booboom** [comment]
![image](https://user-images.githubusercontent.com/24515720/47012831-d3d40100-d177-11e8-97bf-27c825e3222c.png)
本地和github托管页面报错信息。

**Comment by booboom** [comment]
![image](https://user-images.githubusercontent.com/24515720/47012856-eb12ee80-d177-11e8-9375-e8b6424a6625.png)
接口测试工具，访问正常。

**Comment by metowolf** [comment]
可以尝试本机网络直接访问 https://api.i-meto.com/
如果无法访问，就证明被墙了。

**Comment by booboom** [comment]
@metowolf 访问不了，被墙了也不应该啊，getman上可以访问到。
蓝廋。
