### ISSUE TITLE
网易云获取图片的链接已经更新

### ISSUE THREAD

**Issue by zhuhanzhuhan** [metowolf/Meting#63]
最近网易云音乐没法获取歌曲封面了
发现网易云歌曲封面图片的链接从p3.music.126.net改为了p2.music.126.net
望修正

**Comment by lwl12** [comment]
@zhuhanzhuhan https://p3.music.126.net/aQhLC9kR4Z7iiwIuynXnQA==/14402502812253006.jpg?param=300y300
我这看 p3 没问题啊，能给一下具体出问题的歌曲吗

**Comment by zhuhanzhuhan** [comment]
看来p1 p2 p3只是三个不同的图片服务器？也可能跟我网络环境有关，先close issue吧

**Comment by metowolf** [comment]
这是网易的 CDN 域名分片，有 p1-4 四个域名，使用上无区别。
