### ISSUE TITLE
播放器音量调节有问题

### ISSUE THREAD

**Issue by David-Lei** [metowolf/Meting#65]
dalao，
您的音乐播放器的音量调节，只能选择开或关，无法正常调节音量。
把音量条点出来，再进行拖动的话，则声音会直接被关成静音，且无法在打开，只能刷新页面。
不知道会不会是我的博客的问题QWQ
谢谢

**Comment by metowolf** [comment]
Meting 仅为后端 API 类，该问题建议转 https://github.com/MoePlayer/APlayer 进行反馈，并请附上测试地址和浏览器信息方便复现。
