### ISSUE TITLE
php 5.4不是必须的

### ISSUE THREAD

**Issue by ericzane** [metowolf/Meting#66]
手头有台服务器，只有php5.3，测试了下只有一个语句不能通过，修改后可以正常运行
就是`$data = $api->format(true)->search('Soldier', [
    'page' => 1,
    'limit' => 50
]);`
改为`$data = $api->format(true)->search('Soldier', array(
    'page' => 1,
    'limit' => 50
));`

**Comment by metowolf** [comment]
目前 Meting.php 文件最低可以支持到 PHP 5.2

![image](https://user-images.githubusercontent.com/2666735/50944945-8395e200-14cd-11e9-8d58-af8bf483b2b0.png)

但根据 PHP 支持周期表，Meting 目前只保证 PHP 7.1 及其以上版本的正常运行，建议尽快升级
