### ISSUE TITLE
a part of netease music can't be found

### ISSUE THREAD

**Issue by ENDsoft233** [metowolf/Meting#72]
有些网易云音乐里的歌曲用API搜不出来，比如《勾指起誓》、《不潮不用花钱》。

**Comment by yiyungent** [comment]
我这没有问题的哦，   可能是被暂时屏蔽了吧，改改cookie试试

`
$api = new Meting('netease');   
$data =  $api->format(true)->search("勾指起誓");
`

![image](https://user-images.githubusercontent.com/16939388/54874979-a54a0880-4e30-11e9-9b12-c110e170d0ec.png)

**Comment by ENDsoft233** [comment]
> 我这没有问题的哦， 可能是被暂时屏蔽了吧，改改cookie试试
> 
> `$api = new Meting('netease'); $data = $api->format(true)->search("勾指起誓");`
> 
> ![image](https://user-images.githubusercontent.com/16939388/54874979-a54a0880-4e30-11e9-9b12-c110e170d0ec.png)

改成自己的cookie以后就可以搜索了XD

**Comment by ENDsoft233** [comment]
怎么感觉时炸时不炸的， 现在勾指起誓可以搜，不潮不用花钱又不行了
