### ISSUE TITLE
Meto 大佬可以考虑下接口简洁化嘛？

### ISSUE THREAD

**Issue by Dreamer-Paul** [metowolf/Meting#74]
RT，我发现如果要供一个播放器使用你的 API，需要发多次 XHR 请求分别请求一次歌曲信息和歌词内容。如果有翻译还得额外请求一次，食用起来略嫌麻烦。

我自己分析找到了 Meting 使用的部分网易接口，发现部分接口并不需要 `params` 和 `encSecKey` 参数就能获得内容，不解为什么还要额外发送它们。

而近期我打算发布一个精简轻量的播放器（Kico Player Mini），这个东西在我博客的 [文章](https://paugram.com/tech/redis-learning-notes.html) 里也有 Demo。由于本人穷的慌，没钱完善服务器资源，可能无法给予用户最好的体验。暂时打算考虑食用一下大佬的接口，不知道大佬能否完善下 Meting 或是为我提供帮助？

**Comment by metowolf** [comment]
Meting 库更主要是为开发者提供方便的解析接口，暂不会考虑做大的调整。如果有需要可以基于 Meting 自行封装更精简的 API 接口。

MetingJS 所使用的 API 需要对歌单、专辑进行解析，为了方便分流，减少后端压力，需要拆分请求。

**Comment by Dreamer-Paul** [comment]
现在 Meting 的解析基本上等同于照搬网易现有 API 上的东西... 我是没明白拆分开来怎么就能减少后端压力了...

**Comment by metowolf** [comment]
例如一些 1000+ 的歌单，如果将歌词、歌曲链接合并解析，后端需要向上游同时发送 2000 个请求，这个是没办法承受的。

**Comment by Dreamer-Paul** [comment]
如果是自建的话给单曲还是歌单提供一个缓存选项不就好多了嘛... 这样又精简速度又快请求也少

**Comment by metowolf** [comment]
非代码问题先关闭 issue 了，关于后端 API 的具体实现细节可以在 Telegram 进一步讨论。
