### ISSUE TITLE
测试qq音乐接口无法使用

### ISSUE THREAD

**Issue by zhangziran** [metowolf/Meting#75]
基于MKOnlineMusicPlayer最新，和Meting1.5.6

访问外链会直接403，另外酷狗接口可否考虑支持https呢。

**Comment by philipsc** [comment]
收费且提示需要桌面版软件播放的QQ音乐无法解析！

**Comment by DanielZhang17** [comment]
研究了一下，腾讯现在桌面app直接把密钥对绑定用户了所以这个有点麻烦。还有就是看了一下1.5.6的代码，没有找到调用的接口，所以解析不了是理所当然的，希望作者来解决一下

**Comment by DanielZhang17** [comment]
我用桌面客户端抓了一下几种不同的音质得出的结论是
无损用的如下接口
`http://211.152.148.15/amobile.music.tc.qq.com/F000004IBkqX2IRgmV.flac?guid=guid&vkey=vkey&uin=?&fromtag=80`
其他音质试听都是ogg，如果下载则有常规MP3且guid对应的vkey都和用户直接对应， fromtag=140.
另外前面地址的域名也是用JSON返回的
所以用桌面客户端抓包无解，可能需要抓移动客户端的GET请求

**Comment by ericzane** [comment]
我这使用没问题，是不是国外服务器问题？

**Comment by DanielZhang17** [comment]
有可能，国内服务器用不起

**Comment by metowolf** [comment]
感谢反馈
经过测试，QQ 音乐 API 目前在国内服务器上使用正常
