### ISSUE TITLE
网易云失效和QQ部分歌曲无法解析

### ISSUE THREAD

**Issue by haozicloud** [metowolf/Meting#79]
如题：网易云失效和QQ部分歌曲无法解析
测试了蛮多歌曲，少数可以解析。

**Comment by yiyungent** [comment]
尝试切换一下你的cookie
```
$api->cookie('your cookie')
```
我这一切正常
![image](https://user-images.githubusercontent.com/16939388/61108646-77f39a00-a4b5-11e9-9440-6e894915d490.png)

**Comment by metowolf** [comment]
建议提供无法解析的歌曲 ID 方便排查

**Comment by haozicloud** [comment]
换了服务器正常了，应该是服务器被网易屏蔽了
