### ISSUE TITLE
QQ音乐挂了

### ISSUE THREAD

**Issue by philipsc** [metowolf/Meting#82]
![QQ截图20190817103105](https://user-images.githubusercontent.com/31801469/63205652-353b6800-c0da-11e9-9dda-5d72d2e28f98.jpg)

**Comment by metowolf** [comment]
可以自定替换地址为 https://dl.stream.qqmusic.qq.com/

**Comment by philipsc** [comment]
替换哪个位置啊

**Comment by metowolf** [comment]
在外部程序调用处进行替换，Meting 只负责从 QQ 音乐 API 进行抓取，对原始地址不作修改和处理

经过测试，目前 Meting 针对 QQ 音乐返回的地址为 http://ws.stream.qqmusic.qq.com/ （不带 HTTPS）

**Comment by philipsc** [comment]
已经解决了，谢谢
