### ISSUE TITLE
kugou和baidu的song()接口挂了

### ISSUE THREAD

**Issue by slowvic** [metowolf/Meting#83]
kugou：
返回 操作太频繁...
没搞明白是基于什么判断的。
baidu：
返回 {"error_message":"failed","errno":22001,"error_code":22001}

**Comment by Dreamiva** [comment]
> 返回 操作太频繁...
> 没搞明白是基于什么判断的。
IP限制  尝试修改为125.64.107.18试以下

**Comment by slowvic** [comment]
不好意思，没明白。
是加请求头还是设代理？

**Comment by Dreamiva** [comment]
> 不好意思，没明白。
> 是加请求头还是设代理？

加请求头就可以

**Comment by slowvic** [comment]
好的，谢了。正常返回了，继续观察。
百度的那个知道什么原因么？

**Comment by Dreamiva** [comment]
> 好的，谢了。正常返回了，继续观察。
> 百度的那个知道什么原因么？

百度的没用过，方便的话留一下报错信息把

**Comment by Dreamiva** [comment]
> 好的，谢了。正常返回了，继续观察。
> 百度的那个知道什么原因么？

百度的没有用过，酷狗你可以添加这个头'Referer' => 'http://www.kugou.com/webkugouplayer/flash/webKugou.swf',  作者最新的源码里面好像没有这个了

**Comment by slowvic** [comment]
百度的报错信息 {"error_message":"failed","errno":22001,"error_code":22001}

**Comment by xueshuai0922** [comment]
这么多歌曲从哪里来的

**Comment by yoyling** [comment]
> 这么多歌曲从哪里来的

你可真逗，当然是获取的网易音乐、QQ音乐等里面的资源。

**Comment by Dreamiva** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
