### ISSUE TITLE
网易云歌曲无法播放

### ISSUE THREAD

**Issue by Nikati** [metowolf/Meting#86]
Taylor Swift的歌曲我测试大部分无法解析

**Comment by metowolf** [comment]
Taylor Swift 歌曲均属于付费资源

**Comment by Nikati** [comment]
目前有没有什么解决办法呢

**Comment by Nikati** [comment]
> 
> 
> Taylor Swift 歌曲均属于付费资源

目前有没有什么解决办法呢

**Comment by metowolf** [comment]
付费资源无法直接绕过，可以考虑设置会员的 cookie 来实现解析

**Comment by Nikati** [comment]
> 
> 
> 付费资源无法直接绕过，可以考虑设置会员的 cookie 来实现解析

十分感谢大佬给出解决思路。希望以后还能有交流！
