### ISSUE TITLE
强烈建议加入咪咕音乐

### ISSUE THREAD

**Issue by tmsdy** [metowolf/Meting#87]
现在已经接入的网易，qq，虾米等对于一些特定版权的歌要么是无法听，要么是付费。只有咪咕音乐简直开挂，几乎全免费。。

**Comment by tmsdy** [comment]
大佬有没有已阅   是考虑还是不考虑呢？？

**Comment by tmsdy** [comment]
折腾了半天，还是自己把Migu加上了，暂时只解析了音频url，图片url，歌词。 其它的暂时没管了。

**Comment by tmsdy** [comment]
fork了，并且代码也更新了下

**Comment by Cydianrice** [comment]
@tmsdy 
搜索呢？

**Comment by Cydianrice** [comment]
好像你修改的，在高并发下不能用了。
不知可否将下面别人研究的api内置到meting中?

https://github.com/jsososo/MiguMusicApi

**Comment by tmsdy** [comment]
具体是啥症状？我也不会php也不会js，完全是照着现有的网易qq的改的，框架啥的我也没动，我看了下你发的这项目api格式好像差不多，你也可以试试自己折腾的。

**Comment by haoziz** [comment]
此接口有qps限制，需要网页版的v3接口方可解除限制。

**Comment by haoziz** [comment]
> 好像你修改的，在高并发下不能用了。
> 不知可否将下面别人研究的api内置到meting中?
> 
> https://github.com/jsososo/MiguMusicApi

此项目和tmsdy那个用的是同一个接口
