### ISSUE TITLE
网易音乐歌单只能获取一首了

### ISSUE THREAD

**Issue by ericzane** [metowolf/Meting#94]
如题

**Comment by metowolf** [comment]
https://github.com/metowolf/MetingJS/issues/48
已经在 1.5.8 版本修复

**Comment by ericzane** [comment]
> [metowolf/MetingJS#48](https://github.com/metowolf/MetingJS/issues/48)
> 已经在 1.5.8 版本修复

抱歉，我看code里还写着1.5.7以为没改

**Comment by ericzane** [comment]
> [metowolf/MetingJS#48](https://github.com/metowolf/MetingJS/issues/48)
> 已经在 1.5.8 版本修复

刚刚更新了，发现部分歌单是正常了，但部分歌单从1首变10首，还是少了

**Comment by RecluseWind** [comment]
可以改用网易的另一个端口https://music.163.com/weapi/v3/playlist/detail 
不过这个端口需要对参数加密再传，先aes加密再rsa加密。
